### ISSUE TITLE
未完全激活，已获得设备管理员，重启软件是未激活

### ISSUE THREAD

**Issue by Aurora-Simba** [iamr0s/Dhizuku#10]
[shproc] Process[pid=12652, hasExited=false]

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Unexpected @ProvisioningPreCondition: 99
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9667)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8494)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:259)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:10007)
	at android.os.Binder.shellCommand(Binder.java:1073)
	at android.os.Binder.onTransact(Binder.java:901)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6054)
	at android.os.Binder.execTransactInternal(Binder.java:1331)
	at android.os.Binder.execTransact(Binder.java:1268)
[shproc] Process[pid=12652, hasExited=true, exitcode=0]
![Screenshot_2023-05-11-20-32-49-77_581242ce254f386c2386b7887f61c792](https://github.com/iamr0s/Dhizuku/assets/106955617/496732fa-2800-41ad-a5ff-6670135b8336)

**Comment by iamr0s** [comment]
[CoolAPK Article](https://www.coolapk.com/feed/45819359?shareKey=MGQ3YjZhZTY5N2I1NjQ1Y2U0MWE~&shareUid=1581760&shareFrom=com.coolapk.market_13.1.1)

OPPO对设备所有者做出了限制，想要完全激活自己用MT默认签名进行签名。

**Comment by Aurora-Simba** [comment]
依然不成功
[shproc] Process[pid=16731, hasExited=false]

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9667)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8494)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:259)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:10007)
	at android.os.Binder.shellCommand(Binder.java:1073)
	at android.os.Binder.onTransact(Binder.java:901)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6054)
	at android.os.Binder.execTransactInternal(Binder.java:1331)
	at android.os.Binder.execTransact(Binder.java:1268)
[shproc] Process[pid=16731, hasExited=true, exitcode=0]

**Comment by Aurora-Simba** [comment]
签名所有者EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US

**Comment by iamr0s** [comment]
![image](https://github.com/iamr0s/Dhizuku/assets/41138521/62969807-cdd0-42e5-bf70-54b8caa23cad)

**Comment by iamr0s** [comment]
严格按照教程步骤来

**Comment by iamr0s** [comment]
那就是没禁用干，按照文章内说的执行`dumpsys account`
type后面一般是包名或与包名相关。

**Comment by iamr0s** [comment]
经我手激活的ColorOS就有数十台，其中大部分都是没有禁用我的oppo或我的Realme等。
根据包名找应用就行

**Comment by Aurora-Simba** [comment]
dingtalk万恶之源，移除账号自己又登录回来了，感谢，麻烦您了

**Comment by iamr0s** [comment]
是的，我在那篇文章中已经指出，推荐使用 [雹](https://github.com/aistra0528/Hail/) 进行冻结。

冻结通常会比移除有效：

1. 解冻后账号依然存在，不影响账户的数据
2. 移除后部分应用工作可能不正常，因此推荐冻结
