### ISSUE TITLE
Exception occurred while executing 'set-device-owner'

### ISSUE THREAD

**Issue by kaorlol** [iamr0s/Dhizuku#34]
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Trying to set the device owner (com.rosan.dhizuku/.server.DhizukuDAReceiver), but the user already has a profile owner (com.google.android.gms/.kids.account.receiver.ProfileOwnerReceiver).
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:10687)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:9364)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:264)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:87)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11119)
        at android.os.Binder.shellCommand(Binder.java:1094)
        at android.os.Binder.onTransact(Binder.java:911)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6328)
        at android.os.Binder.execTransactInternal(Binder.java:1362)
        at android.os.Binder.execTransact(Binder.java:1301)
        
How can I fix this?

**Comment by diabl0w** [comment]
following... have users reporting same issue. they are running android 14 samsung oneui 6

**Comment by rifting** [comment]
sorry for the necropost, but if anyone else is experiencing it you need to remove family link from your device

**Comment by rifting** [comment]
can you do `adb shell dpm list-owners` for me?

**Comment by francois072** [comment]
> can you do `adb shell dpm list-owners` for me?

`adb shell dpm list-owners
no owners`

**Comment by rifting** [comment]
Is dhizuku a device admin (in settings > search "device admin apps"?)

**Comment by francois072** [comment]
> Is dhizuku a device admin (in settings > search "device admin apps"?)

Yes, Dhizuku is set as device admin and is also authorized in Shizuku. 
Running `dpm set-device-owner --user 0 com.rosan.dhizuku/.server.DhizukuDAReceiver` does disable Dhizuku as device admin while still giving the same error metioned above.

**Comment by s1204IT** [comment]
This cannot be set if a Google account and other exists due to Android specifications.
Check the list of accounts in the Android Settings app, delete them all, and then try `set-device-owner` again.
