### ISSUE TITLE
Not allowed to set the device owner because there are already some accounts on the device

### ISSUE THREAD

**Issue by vfishv** [iamr0s/Dhizuku#35]
Android 14

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:10687)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:9364)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:264)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:87)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11119)
	at android.os.Binder.shellCommand(Binder.java:1094)
	at android.os.Binder.onTransact(Binder.java:911)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6328)
	at android.os.Binder.execTransactInternal(Binder.java:1362)
	at android.os.Binder.execTransact(Binder.java:1301)

**Comment by fu8765** [comment]
@vfishv https://github.com/iamr0s/Dhizuku/discussions/19
