### ISSUE TITLE
Device admin activated, but need device owner

### ISSUE THREAD

**Issue by ashpro1212** [iamr0s/Dhizuku#36]
Hello there im new to these things and also kinda a newbie to github so sorry if idk what im talking about when i try to use Dhizuku with shizuku i keep running into Device admin activated, but need device owner. "ConsoleError(code=1, read=, error=java.lang.RuntimeException: Can't set package ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.DhizukuDAReceiver} as device owner.
	at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:204)
	at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
	at com.android.commands.dpm.Dpm.main(Dpm.java:41)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)"

**Comment by fu8765** [comment]
@ashpro1212 have you tried these https://github.com/iamr0s/Dhizuku/discussions/19

**Comment by catmeowjiao** [comment]
I'm the same way

**Comment by catmeowjiao** [comment]
```
 adb shell dpm set-device-owner com.rosan.dhizuku/.server.DhizukuDAReceiver
java.lang.RuntimeException: Can't set package ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.DhizukuDAReceiver} as device owner.
	at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:149)
	at com.android.commands.dpm.Dpm.onRun(Dpm.java:96)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.dpm.Dpm.main(Dpm.java:41)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
```

**Comment by DARK7BEAST** [comment]
i too follow each step. and getting same error

**Comment by incapdns** [comment]
I even tried to format my phone without success.

**Comment by puppykickr** [comment]
i am having the same issue...

ConsoleError(code=255, read=, error=
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9766)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8703)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:10085)
	at android.os.Binder.shellCommand(Binder.java:958)
	at android.os.Binder.onTransact(Binder.java:842)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6983)
	at android.os.Binder.execTransactInternal(Binder.java:1197)
	at android.os.Binder.execTransact(Binder.java:1151)
)
	at f5.s.g(SourceFile:296)
	at s5.a.u(Unknown Source:8)
	at g6.g0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)

**Comment by elderwolf123** [comment]
Same here, I even tried to disable every app outside Shizuku and Dhizuku but it didn't make a difference

**Comment by 771SAINI** [comment]
Tried disabling permission monitoring in Developer options ? It should work

**Comment by s1204IT** [comment]
This cannot be set if a Google account and other exists due to Android specifications.
Check the list of accounts in the Android Settings app, delete them all, and then try `set-device-owner` again.

**Comment by s1204IT** [comment]
This occurs because `android.software.device_admin` is missing. Adding it requires rooting or powerful privileges to forcibly overwrite the system, so it is nearly impossible to operate by default.
