### ISSUE TITLE
Dhizuku Not Activating On My Android 12 

### ISSUE THREAD

**Issue by AngelMende3z** [iamr0s/Dhizuku#60]
When I try to activate Dhizuku:
ConsoleError(code=255, read=, error=
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9498)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8434)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9817)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6966)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
)
	at f5.s.g(SourceFile:296)
	at s5.a.u(Unknown Source:8)
	at g6.g0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)

**Comment by AngelMende3z** [comment]
![Screenshot_20240624-190002](https://github.com/iamr0s/Dhizuku/assets/165435968/afb308b2-391c-438c-9f27-329158d2068f)
I have already tried to follow the instructions and as you can see it keeps saying that it cannot be done.

**Comment by gabrielparca** [comment]
Similar thing happens to me

https://github.com/user-attachments/assets/1d5e3728-7284-442f-8888-5d496f7e6ca3



ConsoleError(code=255, read=, error=
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:11865)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:10467)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:257)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:87)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:12305)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:7077)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
)
	at f5.s.g(SourceFile:296)
	at s5.a.u(Unknown Source:8)
	at g6.g0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)

**Comment by andrewzaycew** [comment]
https://github.com/iamr0s/Dhizuku/discussions/19

**Comment by gabrielparca** [comment]
thank you

**Comment by gabrielparca** [comment]
> #19

thank you
