### ISSUE TITLE
启动Dhizuku时崩溃

### ISSUE THREAD

**Issue by BinTianqi** [iamr0s/Dhizuku#79]
我在安卓14上打开Dhizuku时崩溃

Dhizuku版本：https://github.com/iamr0s/Dhizuku/actions/runs/10841438839

日志：

```
FATAL EXCEPTION: main
Process: com.rosan.dhizuku, PID: 23364
java.lang.RuntimeException: Unable to create application com.rosan.dhizuku.App: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.RunningService} does not require android.permission.BIND_JOB_SERVICE permission
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7403)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.RunningService} does not require android.permission.BIND_JOB_SERVICE permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3187)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:455)
	at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:96)
	at e1.f.n(SourceFile:1)
	at e1.i.a(SourceFile:9)
	at M2.e.m0(SourceFile:29)
	at com.rosan.dhizuku.App.onCreate(SourceFile:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1386)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7398)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:4823)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enqueue(JobSchedulerService.java:5070)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:238)
	at android.os.Binder.execTransactInternal(Binder.java:1500)
	at android.os.Binder.execTransact(Binder.java:1444)
```

**Comment by iamr0s** [comment]
尝试最新的打包，已修复此问题 39100ff
