### ISSUE TITLE
dhizuku is crashing continuously

### ISSUE THREAD

**Issue by zwyxtu** [iamr0s/Dhizuku#80]
I updated to this version: 2.9 (12)
https://github.com/iamr0s/Dhizuku/actions/runs/11079359356

SDK: 34
PRODUCT_NAME: RMX3834
DEVICE_NAME: RE5C9F
BOARD_NAME: ums9230_hulk
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi
MANUFACTURER: realme
BRAND: realme
MODEL: RMX3834

FATAL EXCEPTION: main
Process: com.rosan.dhizuku, PID: 28055
java.lang.RuntimeException: Unable to create application com.rosan.dhizuku.App: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.RunningService} does not require android.permission.BIND_JOB_SERVICE permission
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7147)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8394)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.rosan.dhizuku/com.rosan.dhizuku.server.RunningService} does not require android.permission.BIND_JOB_SERVICE permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:458)
	at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:96)
	at A0.a.n(SourceFile:1)
	at X0.h.a(SourceFile:9)
	at P0.i.y0(SourceFile:29)
	at com.rosan.dhizuku.App.onCreate(SourceFile:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7141)
	... 9 more

**Comment by iamr0s** [comment]
try the [lastest build action](https://github.com/iamr0s/Dhizuku/actions), fix it in 39100ff

**Comment by zwyxtu** [comment]
🫶❤️ Thank you! Problem solved!!!
![Screenshot_20241001-112055](https://github.com/user-attachments/assets/6f546d38-c6ab-4a20-9c2d-ab614f7ba087)
