### ISSUE TITLE
Android 14 bug

### ISSUE THREAD

**Issue by TDD788** [iamr0s/Dhizuku#82]
dpm set-device-owner com.rosan.dhizuku>

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:10842)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:9488)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:264)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:87)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11275)
        at android.os.Binder.shellCommand(Binder.java:1230)
        at android.os.Binder.onTransact(Binder.java:1043)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6423)
        at android.os.Binder.execTransactInternal(Binder.java:1505)
        at android.os.Binder.execTransact(Binder.java:1444)

**Comment by Geo25rey** [comment]
Read instructions: https://github.com/iamr0s/Dhizuku/discussions/19#already_accounts
