### ISSUE TITLE
调用API时崩溃

### ISSUE THREAD

**Issue by BinTianqi** [iamr0s/Dhizuku#99]
调用API时，client和server同时崩溃

<details>
<summary>client崩溃日志</summary>

```
FATAL EXCEPTION: main
Process: com.bintianqi.owndroid, PID: 25386
java.lang.RuntimeException: android.os.DeadObjectException
	at com.rosan.dhizuku.api.Dhizuku.remoteTransact(Dhizuku.java:210)
	at com.rosan.dhizuku.api.DhizukuBinderWrapper.transact(DhizukuBinderWrapper.java:50)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.isAdminActive(IDevicePolicyManager.java:7612)
	at android.app.admin.DevicePolicyManager.isAdminActiveAsUser(DevicePolicyManager.java:4357)
	at android.app.admin.DevicePolicyManager.isAdminActive(DevicePolicyManager.java:4347)
	at com.bintianqi.owndroid.dpm.DPMKt.isDeviceAdmin(DPM.kt:78)
	at com.bintianqi.owndroid.MainActivityKt$HomePage$1$1.invokeSuspend(MainActivity.kt:349)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@431a07c, androidx.compose.runtime.BroadcastFrameClock@3ef4d05, StandaloneCoroutine{Cancelling}@d39815a, AndroidUiDispatcher@c81af8b]
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at com.rosan.dhizuku.api.Dhizuku.remoteTransact(Dhizuku.java:208)
	... 19 more
```
</details>

<details>
<summary>Dhizuku崩溃日志</summary>

```
FATAL EXCEPTION: main
Process: com.rosan.dhizuku, PID: 25433
java.lang.RuntimeException: Unable to create application com.rosan.dhizuku.App: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.rosan.dhizuku/.server.RunningService }: app is in background uid UidRecord{9aef18b u0a276 CEM  bg:+27ms idle change:idle|cached|procstate procs:0 seq(565746,565746)} caps=-------
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7403)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.rosan.dhizuku/.server.RunningService }: app is in background uid UidRecord{9aef18b u0a276 CEM  bg:+27ms idle change:idle|cached|procstate procs:0 seq(565746,565746)} caps=-------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1946)
	at android.app.ContextImpl.startService(ContextImpl.java:1901)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at com.rosan.dhizuku.App.onCreate(SourceFile:48)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1386)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7398)
	... 9 more
```
</details>

系统：Android14
Dhizuku版本： cc71993
API版本：v2.5.3

（设备开机后Dhizuku也会崩溃一次，日志相同）

**Comment by sbmatch** [comment]
呜呜呜  我也是遇到了绑定userService后调用其中的接口就崩溃,目前使用的是DhizukuBinderWrapper方式

```
   private DevicePolicyManager(String targetPackage){
        android.app.admin.DevicePolicyManager dpm2 = (android.app.admin.DevicePolicyManager) 
                ContextUtil.createPackageContext(targetPackage).getSystemService(Context.DEVICE_POLICY_SERVICE);
        IInterface anInterface = (IInterface) ReflectUtils.getObjectField(dpm2, "mService");
        switch (targetPackage){
            case "com.rosan.dhizuku": //适配Dhizuku
                if (anInterface instanceof DhizukuBinderWrapper)  dpm = dpm2;
                ReflectUtils.setObjectField(dpm2, 
                        "mService", 
                        IDevicePolicyManager.Stub.asInterface(Dhizuku.binderWrapper(anInterface.asBinder())));
                dpm = dpm2;
                break;
            default:

        }

    }
    public static DevicePolicyManager get(){
        adminComponent = getDeviceOwnerComponent();
        devicePolicyManager = new DevicePolicyManager(getDeviceOwnerComponent().getPackageName());
        return devicePolicyManager;
    }
```
但是用userService的方式就不行
``` java
 DhizukuUserServiceFactory.getInstance().bindUserService(new OnBinderCallbackListener() {
                @Override
                public void onUserServiceReady(IBinder service, String ImplClass) throws RemoteException {
                    logger.info("onUserServiceReady: "+ImplClass);
                    IUserService userService = IUserService.Stub.asInterface(service);
                    try {
                        PopTip.show("invoke method isPackageSuspended "+userService.isPackageSuspended(BuildConfig.APPLICATION_ID));
                    } catch (RemoteException e) {
                        logger.severe(Log.getStackTraceString(e));
                    }
                }
                @Override
                public void onUserServiceDisconnected(String ImplClass) throws RemoteException {

                }
            });
```

崩溃日志
``` 
03-02 13:25:54.617 22399 22399 I izukuUserServiceFactory: Dhizuku 用户服务已连接!
03-02 13:25:54.617 22399 22399 I global  : onUserServiceReady: com.sbmatch.deviceopt.Interface.DhizukuUserServiceImpl
03-02 13:25:54.618 22399 22399 E global  : android.os.DeadObjectException
03-02 13:25:54.618 22399 22399 E global  :      at android.os.BinderProxy.transactNative(Native Method)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.BinderProxy.transact(BinderProxy.java:628)
03-02 13:25:54.618 22399 22399 E global  :      at ma.DeviceOptimizeHelper.IUserService$Stub$Proxy.isPackageSuspended(IUserService.java:429)
03-02 13:25:54.618 22399 22399 E global  :      at com.sbmatch.deviceopt.MainActivity$1.onUserServiceReady(MainActivity.java:123)
03-02 13:25:54.618 22399 22399 E global  :      at com.sbmatch.deviceopt.Interface.DhizukuUserServiceFactory$1.onServiceConnected(DhizukuUserServiceFactory.java:37)
03-02 13:25:54.618 22399 22399 E global  :      at com.rosan.dhizuku.api.DhizukuServiceConnection.lambda$onServiceConnected$0$com-rosan-dhizuku-api-DhizukuServiceConnection(DhizukuServiceConnection.java:20)
03-02 13:25:54.618 22399 22399 E global  :      at com.rosan.dhizuku.api.DhizukuServiceConnection$$ExternalSyntheticLambda0.run(Unknown Source:6)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Handler.handleCallback(Handler.java:1013)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Handler.dispatchMessage(Handler.java:101)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Looper.loopOnce(Looper.java:226)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Looper.loop(Looper.java:328)
03-02 13:25:54.618 22399 22399 E global  :      at com.kongzue.baseframework.BaseFrameworkSettings$1.run(BaseFrameworkSettings.java:59)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Handler.handleCallback(Handler.java:1013)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Handler.dispatchMessage(Handler.java:101)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Looper.loopOnce(Looper.java:226)
03-02 13:25:54.618 22399 22399 E global  :      at android.os.Looper.loop(Looper.java:328)
03-02 13:25:54.618 22399 22399 E global  :      at android.app.ActivityThread.main(ActivityThread.java:9179)
03-02 13:25:54.618 22399 22399 E global  :      at java.lang.reflect.Method.invoke(Native Method)
03-02 13:25:54.618 22399 22399 E global  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
03-02 13:25:54.618 22399 22399 E global  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
03-02 13:25:54.618 22399 22399 E izukuUserServiceFactory: Dhizuku 用户服务断开连接 com.sbmatch.deviceopt.Interface.DhizukuUserServiceImpl
```

**Comment by s1204IT** [comment]
This is an issue in v2.9.

The solution to this is to always call `stopUserService` and `unbindUserService` after processing with your own user service.

Without this process, the inappropriate pipe will remain open when the client app is closed, and the `DeadObjectException` will continue to be thrown, as shown in your log.

An easy way to fix this without changing your current code is to simply "stop" the Dhizuku app and restart the server.

**Comment by s1204IT** [comment]
现在，我将关闭此问题，因为它目前可以在客户端解决。
